use serde::{Deserialize, Serialize};

use crate::config_store::DeviceConfiguration;
use crate::registry::{boards, sensors};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedFirmware {
    pub configuration_id: String,
    pub file_name: String,
    pub fqbn: String,
    pub source: String,
}

fn escape(value: &str) -> String { value.replace('"', "\\\"") }

pub fn generate(config: &DeviceConfiguration) -> Result<GeneratedFirmware, String> {
    let board = boards().into_iter().find(|b| b.id == config.board_id)
        .ok_or_else(|| format!("Unknown board: {}", config.board_id))?;

    let mut declarations = String::new();
    let mut setup = String::new();
    let mut loop_body = String::new();

    for assignment in &config.assignments {
        let sensor = sensors().into_iter().find(|s| s.id == assignment.sensor_id)
            .ok_or_else(|| format!("Unknown sensor: {}", assignment.sensor_id))?;
        let parameter = sensor.parameters.iter().find(|p| p.id == assignment.parameter_id)
            .ok_or_else(|| format!("Unknown parameter: {}", assignment.parameter_id))?;
        let variable = format!("{}_{}", assignment.sensor_id.replace('-', "_"), assignment.parameter_id.replace('-', "_"));

        match assignment.pin_type.as_str() {
            "digital" => {
                declarations.push_str(&format!("const uint8_t PIN_{} = {};\n", variable.to_uppercase(), assignment.pin));
                setup.push_str(&format!("  pinMode(PIN_{}, INPUT);\n", variable.to_uppercase()));
                loop_body.push_str(&format!("  int {} = digitalRead(PIN_{});\n", variable, variable.to_uppercase()));
            }
            "analog" => {
                declarations.push_str(&format!("const uint8_t PIN_{} = A{};\n", variable.to_uppercase(), assignment.pin.saturating_sub(14)));
                setup.push_str(&format!("  pinMode(PIN_{}, INPUT);\n", variable.to_uppercase()));
                loop_body.push_str(&format!("  int {} = analogRead(PIN_{});\n", variable, variable.to_uppercase()));
            }
            _ => {}
        }

        loop_body.push_str(&format!("  // Maintain.ai signal: {} from {} / {}\n", escape(parameter.signal_type), escape(sensor.name), escape(parameter.name)));
    }

    let source = format!("// Generated by Maintain.ai DeviceOS\n// configuration: {}\n// schema: {}\n// definitions: {}\n\n#include <Arduino.h>\n\n{}\nvoid setup() {{\n  Serial.begin(115200);\n{}\n}}\n\nvoid loop() {{\n{}  delay(1000);\n}}\n", escape(&config.id), escape(&config.schema_version), escape(&config.definition_version), declarations, setup, loop_body);

    Ok(GeneratedFirmware { configuration_id: config.id.clone(), file_name: format!("maintain_ai_{}.ino", config.id), fqbn: board.fqbn.to_string(), source })
}
