use crate::config_store::DeviceConfiguration;
use crate::registry::sensors;
use crate::runtime_firmware::RuntimeFirmware;

fn identifier(value: &str) -> String {
    let mut out = String::new();
    for c in value.chars() {
        if c.is_ascii_alphanumeric() { out.push(c.to_ascii_uppercase()); } else { out.push('_'); }
    }
    out
}

fn escape(value: &str) -> String { value.replace('\\', "\\\\").replace('"', "\\\"") }

pub fn generate(config: &DeviceConfiguration) -> Result<RuntimeFirmware, String> {
    let board = crate::registry::boards().into_iter().find(|b| b.id == config.board_id)
        .ok_or_else(|| format!("Unknown board: {}", config.board_id))?;

    let mut declarations = String::new();
    let mut setup = String::new();
    let mut readings = String::new();

    for assignment in &config.assignments {
        let sensor = sensors().into_iter().find(|s| s.id == assignment.sensor_id)
            .ok_or_else(|| format!("Unknown sensor: {}", assignment.sensor_id))?;
        let parameter = sensor.parameters.iter().find(|p| p.id == assignment.parameter_id)
            .ok_or_else(|| format!("Unknown parameter: {}", assignment.parameter_id))?;
        let key = identifier(&format!("{}_{}", assignment.sensor_id, assignment.parameter_id));
        let pin = if assignment.pin_type == "analog" { format!("A{}", assignment.pin.saturating_sub(14)) } else { assignment.pin.to_string() };
        declarations.push_str(&format!("const uint8_t PIN_{} = {};\n", key, pin));
        setup.push_str(&format!("  pinMode(PIN_{}, INPUT);\n", key));
        let read_expr = if assignment.pin_type == "analog" { format!("analogRead(PIN_{})") } else { format!("digitalRead(PIN_{})") };
        readings.push_str(&format!("  emitReading(\"{}\", \"{}\", (double)({}), \"{}\");\n", escape(sensor.id), escape(parameter.id), read_expr, escape(parameter.unit)));
    }

    let device_literal = match config.device_id.as_deref() {
        Some(id) if !id.is_empty() => format!("\"{}\"", escape(id)),
        _ => "nullptr".to_string(),
    };

    let source = format!(r#"// Generated by Maintain.ai DeviceOS.
// Gateway protocol: one JSON telemetry object per line.
// Protocol: maintain-ai-telemetry v1.0
// Configuration: {config}
#include <Arduino.h>

{decl}
const char* DEVICE_ID = {device_id};
uint64_t sequenceNumber = 0;

void emitReading(const char* sensorId, const char* parameterId, double value, const char* unit) {{
  Serial.print("{{\"reading_type\":\"sensor\",\"protocol\":\"maintain-ai-telemetry\",\"protocol_version\":\"1.0\",\"device_id\":");
  if (DEVICE_ID == nullptr) Serial.print("null"); else {{ Serial.print("\""); Serial.print(DEVICE_ID); Serial.print("\""); }}
  Serial.print(",\"configuration_id\":\"{config}\",\"sequence\":");
  Serial.print(sequenceNumber++);
  Serial.print(",\"sensor_id\":\""); Serial.print(sensorId);
  Serial.print("\",\"parameter_id\":\""); Serial.print(parameterId);
  Serial.print("\",\"value\":"); Serial.print(value, 6);
  Serial.print(",\"unit\":\""); Serial.print(unit);
  Serial.print("\",\"timestamp_ms\":"); Serial.print(millis());
  Serial.println("}}");
}}

void setup() {{
  Serial.begin(115200);
{setup}  delay(100);
  Serial.println("MAINTAIN_AI_SENSOR_NODE_READY");
}}

void loop() {{
{readings}  delay(1000);
}}
"#, config=escape(&config.id), device_id=device_literal, decl=declarations, setup=setup, readings=readings);

    Ok(RuntimeFirmware { configuration_id: config.id.clone(), file_name: format!("maintain_ai_gateway_{}.ino", config.id), fqbn: board.fqbn.to_string(), source })
}
