use serde::{Deserialize, Serialize};

use crate::config_store::DeviceConfiguration;
use crate::registry::{boards, sensors};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuntimeFirmware {
    pub configuration_id: String,
    pub file_name: String,
    pub fqbn: String,
    pub source: String,
}

fn identifier(value: &str) -> String {
    let mut out = String::new();
    for c in value.chars() {
        if c.is_ascii_alphanumeric() { out.push(c.to_ascii_uppercase()); } else { out.push('_'); }
    }
    out
}

pub fn generate(config: &DeviceConfiguration) -> Result<RuntimeFirmware, String> {
    let board = boards().into_iter().find(|b| b.id == config.board_id)
        .ok_or_else(|| format!("Unknown board: {}", config.board_id))?;

    let mut declarations = String::new();
    let mut setup = String::new();
    let mut readings = String::new();
    let mut reading_count = 0usize;

    for assignment in &config.assignments {
        let sensor = sensors().into_iter().find(|s| s.id == assignment.sensor_id)
            .ok_or_else(|| format!("Unknown sensor: {}", assignment.sensor_id))?;
        let parameter = sensor.parameters.iter().find(|p| p.id == assignment.parameter_id)
            .ok_or_else(|| format!("Unknown parameter: {}", assignment.parameter_id))?;
        let key = identifier(&format!("{}_{}", assignment.sensor_id, assignment.parameter_id));
        let pin = if assignment.pin_type == "analog" { format!("A{}", assignment.pin.saturating_sub(14)) } else { assignment.pin.to_string() };
        declarations.push_str(&format!("const uint8_t PIN_{} = {};\n", key, pin));
        setup.push_str(&format!("  pinMode(PIN_{}, INPUT);\n", key));
        let read_expr = if assignment.pin_type == "analog" { format!("analogRead(PIN_{})", key) } else { format!("digitalRead(PIN_{})", key) };
        if reading_count > 0 { readings.push_str(",\n"); }
        readings.push_str(&format!("  emitReading(\"{}\", \"{}\", (double)({}), \"{}\");", sensor.id, parameter.id, read_expr, parameter.unit));
        reading_count += 1;
    }

    let source = format!(r#"// Generated by Maintain.ai DeviceOS.
// Runtime protocol: maintain-ai-telemetry v1.0
// Configuration: {config}
#include <Arduino.h>

{decl}
const char* DEVICE_ID = nullptr;
uint64_t sequenceNumber = 0;

void emitReading(const char* sensorId, const char* parameterId, double value, const char* unit) {{
  Serial.print("{{\"sensor_id\":\""); Serial.print(sensorId);
  Serial.print("\",\"parameter_id\":\""); Serial.print(parameterId);
  Serial.print("\",\"value\":"); Serial.print(value, 6);
  Serial.print(" ,\"unit\":\""); Serial.print(unit);
  Serial.print("\",\"timestamp_ms\":"); Serial.print(millis());
  Serial.print("}}\n");
}}

void emitFrame() {{
  Serial.print("{{\"protocol\":\"maintain-ai-telemetry\",\"protocol_version\":\"1.0\",\"device_id\":");
  if (DEVICE_ID == nullptr) Serial.print("null"); else {{ Serial.print("\""); Serial.print(DEVICE_ID); Serial.print("\""); }}
  Serial.print(",\"configuration_id\":\"{config}\",\"sequence\":");
  Serial.print(sequenceNumber++);
  Serial.print(",\"readings\":[");
{readings}  Serial.print("]}}\n");
}}

void setup() {{
  Serial.begin(115200);
{setup}}}

void loop() {{
  emitFrame();
  delay(1000);
}}
"#, config=config.id, decl=declarations, readings=readings, setup=setup);

    Ok(RuntimeFirmware { configuration_id: config.id.clone(), file_name: format!("maintain_ai_runtime_{}.ino", config.id), fqbn: board.fqbn.to_string(), source })
}
