import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { invoke } from '@tauri-apps/api/core';
import './styles.css';

type Board={id:string;name:string;fqbn:string;digital_pins:number[];analog_pins:number[];buses:string[]};
type Parameter={id:string;name:string;signal_type:string;unit:string;data_type:string;min:number|null;max:number|null};
type Sensor={id:string;name:string;category:string;protocol:string;parameters:Parameter[];required_digital_pins:number;required_analog_pins:number;buses:string[]};
type Machine={id:string;name:string;category:string;signal_ids:string[];components:{id:string;name:string;signal_ids:string[]}[]};
type Selection={sensor_id:string;parameter_ids:string[]};
type Wiring={sensor_id:string;parameter_id:string;signal_type:string;pin:number;pin_type:string;notes:string};
const steps=['Welcome','Machine','Board','Sensors','Review','Wiring','Ready'];
const icons:Record<string,string>={temperature:'°',humidity:'%',vibration:'≈',current:'A',voltage:'V',pressure:'P',flow:'↝',speed:'S',load:'L',rpm:'R',distance:'↔',analog:'⌁',digital:'●'};
function App(){
 const [mode,setMode]=useState<'visual'|'advanced'>('visual'); const [step,setStep]=useState(0); const [boards,setBoards]=useState<Board[]>([]); const [sensors,setSensors]=useState<Sensor[]>([]); const [machines,setMachines]=useState<Machine[]>([]); const [board,setBoard]=useState('arduino-uno-r3'); const [machine,setMachine]=useState('induction-motor'); const [selected,setSelected]=useState<Selection[]>([]); const [connected,setConnected]=useState(false); const [notice,setNotice]=useState(''); const [wiring,setWiring]=useState<Wiring[]>([]);
 useEffect(()=>{Promise.all([invoke<Board[]>('list_boards'),invoke<Sensor[]>('list_sensors'),invoke<Machine[]>('list_machine_types')]).then(([b,s,m])=>{setBoards(b);setSensors(s);setMachines(m)}).catch(()=>setNotice('Preview mode: connect the native app to load hardware data.'))},[]);
 const currentMachine=machines.find(x=>x.id===machine); const chosenSensors=selected.map(x=>({...x,sensor:sensors.find(s=>s.id===x.sensor_id)})).filter(x=>x.sensor); const signalCount=useMemo(()=>selected.reduce((n,x)=>n+x.parameter_ids.length,0),[selected]);
 const toggleSensor=(s:Sensor)=>setSelected(p=>p.some(x=>x.sensor_id===s.id)?p.filter(x=>x.sensor_id!==s.id):[...p,{sensor_id:s.id,parameter_ids:s.parameters.map(x=>x.id)}]);
 const toggleParameter=(sid:string,pid:string)=>setSelected(p=>p.map(x=>x.sensor_id===sid?{...x,parameter_ids:x.parameter_ids.includes(pid)?x.parameter_ids.filter(p=>p!==pid):[...x,pid]}:x));
 const connect=async()=>{try{const ports=await invoke<string[]>('list_serial_ports');setConnected(ports.length>0);setNotice(ports.length?`Found ${ports.length} USB device${ports.length>1?'s':''}.`:'No USB device found. You can continue and connect later.')}catch{setNotice('No USB device found. You can continue and connect later.')}};
 const buildConfig=()=>({id:`visual-${Date.now()}`,machine_type_id:machine,board_id:board,sensors:selected});
 const validate=async()=>{try{const r:any=await invoke('validate_configuration',{request:buildConfig()});setNotice(r.valid?'Everything is compatible.':'Please review the highlighted compatibility issues.');return r.valid}catch{setNotice('Compatibility checking requires the native app.');return false}};
 const loadWiring=async()=>{try{const cfg:any=buildConfig();const r:any=await invoke('generate_wiring',{config:{...cfg,assignments:[]}});setWiring(r.connections||[])}catch{setWiring([])}};
 const next=async()=>{if(step===0)await connect();if(step===3)await validate();if(step===4)await loadWiring();setStep(s=>Math.min(6,s+1));};
 const renderVisual=()=> <>
 {step===0&&<section className="welcome hero-card"><div className="hero-copy"><div className="badge">● SIMPLE SETUP</div><h2>Build a machine monitor without writing code.</h2><p className="muted">Choose your machine, pick the sensors you have, and DeviceOS handles compatibility, pins, wiring and firmware for you.</p><button className="primary big" onClick={next}>Start setup <span>→</span></button><div className="trust"><span>✓ No coding</span><span>✓ Visual wiring</span><span>✓ Guided checks</span></div></div><div className="visual-machine"><div className="machine-ring"><div className="machine-core">⚙</div><div className="bubble b1">🌡 Temperature</div><div className="bubble b2">〽 Vibration</div><div className="bubble b3">A Current</div><div className="bubble b4">R RPM</div></div></div></section>}
 {step===1&&<Wizard title="What are you monitoring?" subtitle="Pick the machine. DeviceOS suggests the signals that matter for it."><div className="card-grid machines">{machines.map(m=><button key={m.id} onClick={()=>setMachine(m.id)} className={machine===m.id?'choice-card selected':'choice-card'}><div className="choice-icon">⚙</div><div><strong>{m.name}</strong><small>{m.components.length} components · {m.signal_ids.length} signals</small></div><span className="radio">{machine===m.id?'✓':''}</span></button>)}</div>{currentMachine&&<div className="suggestion"><strong>DeviceOS will watch</strong><div className="chips">{currentMachine.signal_ids.map(s=><span key={s}>{icons[s]||'•'} {s}</span>)}</div></div>}</Wizard>}
 {step===2&&<Wizard title="Which controller are you using?" subtitle="Choose the board. You do not need to know its technical model number."><div className="card-grid boards">{boards.map(b=><button key={b.id} onClick={()=>setBoard(b.id)} className={board===b.id?'board-card selected':'board-card'}><div className="board-visual"><div className="board-chip">MCU</div><div className="pins" /></div><div><strong>{b.name}</strong><small>USB controller · {b.digital_pins.length} digital · {b.analog_pins.length} analog</small></div><span className="radio">{board===b.id?'✓':''}</span></button>)}</div></Wizard>}
 {step===3&&<Wizard title="What sensors do you have?" subtitle="Tap a sensor, then choose what it should measure."><div className="sensor-grid">{sensors.map(s=>{const a=selected.some(x=>x.sensor_id===s.id);return <div key={s.id} className={a?'sensor-card selected':'sensor-card'}><button className="sensor-main" onClick={()=>toggleSensor(s)}><div className="sensor-icon">◈</div><div><strong>{s.name}</strong><small>{s.parameters.map(p=>p.name).join(' · ')}</small></div><span className="check">{a?'✓':'+'}</span></button>{a&&<div className="parameter-list">{s.parameters.map(p=><label key={p.id}><input type="checkbox" checked={selected.find(x=>x.sensor_id===s.id)?.parameter_ids.includes(p.id)??false} onChange={()=>toggleParameter(s.id,p.id)}/><span>{icons[p.signal_type]||'•'}</span>{p.name}<em>{p.unit}</em></label>)}</div>}</div>})}</div><div className="selection-bar"><span><b>{selected.length}</b> sensors · <b>{signalCount}</b> measurements</span><span>{selected.length?'Ready for compatibility check':'Select sensors'}</span></div></Wizard>}
 {step===4&&<Wizard title="Review your setup" subtitle="DeviceOS checks the technical details in the background."><div className="review-layout"><div className="review-machine"><div className="machine-illustration">⚙</div><strong>{currentMachine?.name}</strong><small>{boards.find(b=>b.id===board)?.name}</small></div><div className="review-list">{chosenSensors.map(x=><div className="review-row" key={x.sensor_id}><span className="sensor-icon small">◈</span><div><strong>{x.sensor?.name}</strong><small>{x.parameter_ids.map(p=>x.sensor?.parameters.find(pp=>pp.id===p)?.name).filter(Boolean).join(' · ')}</small></div><span className="ok">✓ Selected</span></div>)}</div></div>{notice&&<div className="notice">{notice}</div>}</Wizard>}
 {step===5&&<Wizard title="Your wiring plan" subtitle="This is the actual connection plan generated from your configuration."><div className="wiring-board"><div className="board-drawing"><div className="board-label">{boards.find(b=>b.id===board)?.name||'Controller'}</div><div className="board-usb">USB</div><div className="board-pins">{Array.from({length:14},(_,i)=><span key={i}>D{i}</span>)}</div><div className="board-analog">{Array.from({length:6},(_,i)=><span key={i}>A{i}</span>)}</div>{wiring.map((w,i)=><div key={i} className="wire-tag" style={{top:65+i*35,left:120}}>{w.sensor_id} → {w.pin_type==='analog'?`A${Math.max(0,w.pin-14)}`:`D${w.pin}`}</div>)}</div><div className="wire-list">{(wiring.length?wiring:chosenSensors.flatMap(x=>x.parameter_ids.map(pid=>({sensor_id:x.sensor_id,parameter_id:pid,signal_type:'',pin:0,pin_type:'pending',notes:'Pin assignment will be generated by the compatibility engine.'})))).map((w,i)=><div className="wire-row" key={`${w.sensor_id}-${w.parameter_id}-${i}`}><span className="wire-number">{i+1}</span><div><strong>{w.sensor_id}</strong><small>{w.parameter_id}</small></div><span className="wire-target">{w.pin_type==='pending'?'Pending assignment':w.pin_type==='analog'?`A${Math.max(0,w.pin-14)}`:`D${w.pin}`}</span></div>)}</div></div><div className="help-box">🔒 Pin conflicts are checked by DeviceOS before build.</div></Wizard>}
 {step===6&&<Wizard title="You're ready to build" subtitle="Your configuration is ready. Choose Build to generate firmware, or switch to Advanced for technical control."><div className="ready-card"><div className="ready-icon">✓</div><h3>Setup complete</h3><p>{currentMachine?.name} · {selected.length} sensors · {signalCount} measurements</p><div className="ready-actions"><button className="primary big" onClick={async()=>{try{await invoke('generate_runtime_firmware',{config:buildConfig()});setNotice('Firmware generated for this configuration.')}catch{setNotice('Firmware generation requires a fully persisted configuration.')}}}>Build device firmware <span>→</span></button><button className="secondary" onClick={()=>setMode('advanced')}>Open Advanced mode</button></div></div></Wizard>}
 </>;
 const renderAdvanced=()=> <Wizard title="Advanced DeviceOS" subtitle="Direct technical control over the same configuration used by Visual mode."><div className="advanced-grid"><div className="advanced-card"><h3>Configuration</h3><label>Machine<select value={machine} onChange={e=>setMachine(e.target.value)}>{machines.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Board<select value={board} onChange={e=>setBoard(e.target.value)}>{boards.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></div><div className="advanced-card"><h3>Selected sensors</h3>{chosenSensors.map(x=><div className="advanced-row" key={x.sensor_id}><b>{x.sensor?.name}</b><span>{x.parameter_ids.join(', ')}</span></div>)}{!chosenSensors.length&&<p className="muted">No sensors selected in Visual mode yet.</p>}</div><div className="advanced-card full"><h3>Developer actions</h3><p className="muted">These actions operate on the same DeviceOS configuration; nothing is duplicated between modes.</p><div className="advanced-actions"><button className="primary" onClick={validate}>Validate</button><button className="secondary" onClick={loadWiring}>Generate wiring</button><button className="secondary" onClick={async()=>{try{await invoke('generate_runtime_firmware',{config:buildConfig()});setNotice('Runtime firmware generated.')}catch{setNotice('Firmware generation failed.')}}}>Generate firmware</button><button className="secondary" onClick={connect}>Detect USB</button></div></div></div>{notice&&<div className="notice">{notice}</div>}</Wizard>;
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">M</div><div><strong>Maintain.ai</strong><span>DeviceOS</span></div></div><div className="mode-switch"><button className={mode==='visual'?'active':''} onClick={()=>setMode('visual')}>Visual</button><button className={mode==='advanced'?'active':''} onClick={()=>setMode('advanced')}>Advanced</button></div>{mode==='visual'&&<><div className="side-title">SETUP</div><div className="side-steps">{steps.map((s,i)=><button key={s} onClick={()=>i<=step&&setStep(i)} className={i===step?'side-step active':i<step?'side-step done':'side-step'}><span>{i<step?'✓':i+1}</span>{s}</button>)}</div></>}<div className="sidebar-footer"><span className={connected?'status-dot live':'status-dot'} /> {connected?'Device connected':'Waiting for device'}<small>DeviceOS 0.1.0</small></div></aside><main className="main"><header className="topbar"><div><p className="eyebrow">MAINTAIN.AI DEVICEOS</p><h1>{mode==='visual'?'Set up your machine':'Advanced configuration'}</h1></div><div className={connected?'connection live':'connection'}><span className="status-dot" />{connected?'USB device connected':'No device connected'}</div></header><div className="progress"><div style={{width:mode==='visual'?`${(step/6)*100}%`:'100%'}} /></div>{mode==='visual'?renderVisual():renderAdvanced()}<footer className="wizard-footer">{mode==='visual'&&<><button className="back" disabled={step===0} onClick={()=>setStep(s=>Math.max(0,s-1))}>← Back</button>{step>0&&step<6&&<button className="primary" onClick={next}>{step===3?'Check my setup →':step===5?'Finish setup →':'Continue →'}</button>}</>}</footer>{notice&&<div className="toast">{notice}</div>}</main></div>
}
function Wizard({title,subtitle,children}:{title:string;subtitle:string;children:ReactNode}){return <section className="wizard"><div className="wizard-heading"><div><p className="eyebrow">DEVICEOS</p><h2>{title}</h2><p className="muted">{subtitle}</p></div></div>{children}</section>}
export default App;
