import { useEffect, useMemo, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import './styles.css';

type Board={id:string;name:string;fqbn:string;digital_pins:number[];analog_pins:number[];buses:string[]};
type PhysicalPin={id:string;label:string;role:'power'|'ground'|'signal';signal_type?:string};
type Parameter={id:string;name:string;signal_type:string;unit:string;data_type:string;min:number|null;max:number|null};
type Sensor={id:string;name:string;category:string;protocol:string;parameters:Parameter[];required_digital_pins:number;required_analog_pins:number;buses:string[];physical_pins:PhysicalPin[]};
type Machine={id:string;name:string;category:string;signal_ids:string[];components:{id:string;name:string;signal_ids:string[]}[]};
type Selection={sensor_id:string;parameter_ids:string[]};
type Wiring={sensor_id:string;parameter_id:string;signal_type:string;pin:number;pin_type:string;notes?:string};
type DetectedBoard={address:string;port_type:string;protocol:string;board_name?:string;fqbn?:string};

const steps=['Welcome','Machine','Controller','Sensors','Review','Wiring','Build'];
const signalIcon:Record<string,string>={temperature:'°',humidity:'%',vibration:'≈',current:'A',voltage:'V',pressure:'P',flow:'↝',speed:'S',load:'L',rpm:'R',distance:'↔'};

function Wizard({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <section className="wizard"><div className="wizard-heading"><p className="eyebrow">DEVICEOS WORKSPACE</p><h2>{title}</h2><p className="muted">{subtitle}</p></div>{children}</section>}

function App(){
 const[mode,setMode]=useState<'visual'|'advanced'>('visual');
 const[step,setStep]=useState(0);
 const[boards,setBoards]=useState<Board[]>([]); const[sensors,setSensors]=useState<Sensor[]>([]); const[machines,setMachines]=useState<Machine[]>([]);
 const[board,setBoard]=useState('arduino-uno-r3'); const[machine,setMachine]=useState('induction-motor'); const[selected,setSelected]=useState<Selection[]>([]);
 const[wiring,setWiring]=useState<Wiring[]>([]); const[notice,setNotice]=useState(''); const[connected,setConnected]=useState(false);
 const[detected,setDetected]=useState<DetectedBoard[]>([]); const[buildResult,setBuildResult]=useState<any>(null); const[busy,setBusy]=useState(false); const[uploading,setUploading]=useState(false);
 useEffect(()=>{Promise.all([invoke<Board[]>('list_boards'),invoke<Sensor[]>('list_sensors'),invoke<Machine[]>('list_machine_types')]).then(([b,s,m])=>{setBoards(b);setSensors(s);setMachines(m)}).catch(()=>setNotice('DeviceOS native services are unavailable.'))},[]);
 const currentMachine=machines.find(m=>m.id===machine); const currentBoard=boards.find(b=>b.id===board);
 const chosenSensors=selected.map(x=>({...x,sensor:sensors.find(s=>s.id===x.sensor_id)})).filter(x=>x.sensor) as Array<Selection&{sensor:Sensor}>;
 const measurements=useMemo(()=>selected.reduce((n,x)=>n+x.parameter_ids.length,0),[selected]);
 const request=()=>({machine_type_id:machine,board_id:board,sensors:selected});
 const toggleSensor=(s:Sensor)=>setSelected(p=>p.some(x=>x.sensor_id===s.id)?p.filter(x=>x.sensor_id!==s.id):[...p,{sensor_id:s.id,parameter_ids:s.parameters.map(p=>p.id)}]);
 const toggleParam=(sid:string,pid:string)=>setSelected(p=>p.map(x=>x.sensor_id===sid?{...x,parameter_ids:x.parameter_ids.includes(pid)?x.parameter_ids.filter(id=>id!==pid):[...x.parameter_ids,pid]}:x));
 const connect=async()=>{try{const ports=await invoke<string[]>('list_serial_ports');setConnected(ports.length>0);setNotice(ports.length?`${ports.length} USB device${ports.length===1?'':'s'} available.`:'Connect your Arduino by USB when you are ready.')}catch{setNotice('USB status is available in the installed DeviceOS desktop app.')}};
 const validate=async()=>{try{const r:any=await invoke('validate_configuration',{request:request()});if(!r.valid){setNotice(r.errors?.join(' ')||'Configuration needs attention.');return false}setWiring(r.assignments||[]);setNotice(r.warnings?.length?r.warnings.join(' '):'Configuration is compatible.');return true}catch{setNotice('Compatibility checking is unavailable.');return false}};
 const config=(assignments=wiring)=>({id:`device-${machine}-${Date.now()}`,device_id:null,machine_type_id:machine,board_id:board,sensors:selected,assignments,schema_version:'1.0',definition_version:'1.0'});
 const loadWiring=async()=>{const ok=await validate();if(ok)try{await invoke('save_active_configuration',{config:config(wiring)});}catch{}return ok};
 const detect=async()=>{try{const r=await invoke<DetectedBoard[]>('detect_arduino_boards');setDetected(r);setConnected(r.length>0);setNotice(r.length?`Arduino detected on ${r[0].address}.`:'No Arduino detected. Connect it by USB and try again.')}catch(e){setNotice(String(e))}};
 const build=async()=>{setBusy(true);try{const ok=await loadWiring();if(!ok)return;const r:any=await invoke('compile_gateway_firmware',{config:config(wiring)});setBuildResult(r);setNotice(r.success?'Firmware compiled successfully.':'Firmware compilation failed. Open Advanced mode for details.')}catch(e){setNotice(String(e))}finally{setBusy(false)}};
 const upload=async()=>{setUploading(true);try{const r=await invoke<DetectedBoard[]>('detect_arduino_boards');setDetected(r);if(!r.length){setNotice('Connect the Arduino before uploading.');return}if(!buildResult?.success){setNotice('Build the firmware successfully first.');return}const target=r.find(x=>x.fqbn===currentBoard?.fqbn)||r[0];const result:any=await invoke('upload_gateway_firmware',{port:target.address,fqbn:target.fqbn||currentBoard?.fqbn,build_dir:buildResult.output_dir});setNotice(result.success?'Firmware uploaded. Device is ready for MAINTAIN-AI-IoT-Gateway.':result.message||'Upload failed.')}catch(e){setNotice(String(e))}finally{setUploading(false)}};
 const next=async()=>{if(step===0)await connect();if(step===3){if(!selected.length){setNotice('Choose at least one sensor.');return}await validate()}if(step===4){if(!(await loadWiring()))return}setStep(s=>Math.min(6,s+1))};
 const pinLabel=(w:Wiring)=>w.pin_type==='analog'?`A${Math.max(0,w.pin-14)}`:`D${w.pin}`;
 const sensorWiring=(s:Sensor)=>{const ws=wiring.filter(w=>w.sensor_id===s.id);const byParam=(pid:string)=>ws.find(w=>w.parameter_id===pid);return {signalPins:[...new Map(ws.map(w=>[w.pin,pinLabel(w)])).values()],rows:s.physical_pins.map(p=>({physical:p,assignment:p.role==='signal'?byParam(s.parameters.find(x=>x.signal_type===p.signal_type)?.id||''):undefined}))};};
 const visual=<>
  {step===0&&<section className="welcome hero-card"><div className="hero-copy"><div className="badge">● MAINTAIN.AI DEVICEOS</div><h2>Build a real machine monitor, visually.</h2><p className="muted">Start with the machine. DeviceOS then guides you through the controller, sensors, physical wiring and firmware. No Arduino IDE and no command line required.</p><button className="primary big" onClick={next}>Start machine setup <span>→</span></button><div className="trust"><span>✓ Machine-aware</span><span>✓ Physical pin guidance</span><span>✓ Firmware generation</span></div></div><div className="visual-machine"><div className="machine-ring"><div className="machine-core">⚙</div><div className="bubble b1">Temperature</div><div className="bubble b2">Vibration</div><div className="bubble b3">Current</div><div className="bubble b4">RPM</div></div></div></section>}
  {step===1&&<Wizard title="Choose the machine" subtitle="DeviceOS uses the machine profile to show the measurements and sensors that make sense for that equipment."><div className="machine-grid">{machines.map(m=><button key={m.id} className={machine===m.id?'machine-card selected':'machine-card'} onClick={()=>setMachine(m.id)}><div className="machine-card-icon">⚙</div><div className="machine-card-body"><strong>{m.name}</strong><span>{m.category}</span><div className="component-preview">{m.components.map(c=><em key={c.id}>{c.name}</em>)}</div></div><div className="radio">{machine===m.id?'✓':''}</div></button>)}</div>{currentMachine&&<div className="machine-profile"><div><b>{currentMachine.name}</b><span>Machine profile</span></div><div className="signal-cloud">{currentMachine.signal_ids.map(id=><span key={id}>{signalIcon[id]||'•'} {id}</span>)}</div></div>}</Wizard>}
  {step===2&&<Wizard title="Choose your controller" subtitle="Select the board you physically have. DeviceOS will reserve only pins that the selected sensors actually need."><div className="controller-grid">{boards.map(b=><button key={b.id} className={board===b.id?'controller-card selected':'controller-card'} onClick={()=>setBoard(b.id)}><div className="controller-illustration"><div className="controller-chip">MCU</div><div className="controller-header">USB</div><div className="controller-pins left">{b.analog_pins.map(p=><i key={p}>A{p-14}</i>)}</div><div className="controller-pins right">{b.digital_pins.slice(0,8).map(p=><i key={p}>D{p}</i>)}</div></div><div><strong>{b.name}</strong><span>{b.digital_pins.length} digital · {b.analog_pins.length} analog · USB</span></div><div className="radio">{board===b.id?'✓':''}</div></button>)}</div></Wizard>}
  {step===3&&<Wizard title="Add your sensors" subtitle="Pick the hardware you have. DeviceOS knows the physical pins on each sensor and maps its measurements correctly."><div className="sensor-grid">{sensors.map(s=>{const active=selected.some(x=>x.sensor_id===s.id);return <div key={s.id} className={active?'sensor-card selected':'sensor-card'}><button className="sensor-main" onClick={()=>toggleSensor(s)}><div className="sensor-icon">◈</div><div><strong>{s.name}</strong><small>{s.protocol} · {s.physical_pins.length} physical pins</small></div><span className="check">{active?'✓':'+'}</span></button>{active&&<div className="sensor-expanded"><div className="measurement-tags">{s.parameters.map(p=><button key={p.id} className={selected.find(x=>x.sensor_id===s.id)?.parameter_ids.includes(p.id)?'active':''} onClick={()=>toggleParam(s.id,p.id)}>{signalIcon[p.signal_type]||'•'} {p.name}<small>{p.unit}</small></button>)}</div><div className="physical-preview"><span>PHYSICAL SENSOR</span>{s.physical_pins.map(p=><div key={p.id} className={`physical-pin ${p.role}`}><b>{p.label}</b><small>{p.role==='signal'?'connects to Arduino':'connects to '+p.label}</small></div>)}</div></div>}</div>})}</div><div className="selection-bar"><span><b>{selected.length}</b> sensors · <b>{measurements}</b> measurements</span><span>{selected.length?'Ready for compatibility check':'Select your hardware'}</span></div></Wizard>}
  {step===4&&<Wizard title="Review the machine" subtitle="This is the complete setup before DeviceOS creates the wiring plan."><div className="review-hero"><div className="review-machine-art">⚙</div><div><p className="eyebrow">MACHINE PROFILE</p><h3>{currentMachine?.name}</h3><span>{currentBoard?.name}</span></div></div><div className="review-grid">{chosenSensors.map(x=><div className="review-sensor" key={x.sensor_id}><div className="review-sensor-head"><span className="sensor-icon small">◈</span><div><b>{x.sensor.name}</b><small>{x.sensor.protocol}</small></div><span className="ok">✓</span></div><div className="review-measurements">{x.parameter_ids.map(id=>{const p=x.sensor.parameters.find(p=>p.id===id);return p?<span key={id}>{signalIcon[p.signal_type]||'•'} {p.name}</span>:null})}</div></div>)}</div>{notice&&<div className="notice">{notice}</div>}</Wizard>}
  {step===5&&<Wizard title="Connect the sensors" subtitle="Follow the physical connection cards. Power and ground are shown separately; only signal wires consume Arduino GPIO/analog pins."><div className="wiring-workspace"><div className="arduino-panel"><div className="arduino-title"><b>{currentBoard?.name}</b><span>Pin map</span></div><div className="arduino-body"><div className="arduino-analog">{currentBoard?.analog_pins.map(p=><span key={p}>A{p-14}</span>)}</div><div className="arduino-board"><div className="usb-block">USB</div><div className="mcu-block">ATmega<br/>MCU</div><div className="board-name">{currentBoard?.name}</div></div><div className="arduino-digital">{currentBoard?.digital_pins.map(p=><span key={p} className={wiring.some(w=>w.pin===p&&w.pin_type==='digital')?'used':''}>D{p}</span>)}</div></div><div className="legend"><span><i className="dot power"/>Power</span><span><i className="dot signal"/>Signal</span><span><i className="dot ground"/>Ground</span></div></div><div className="connection-list">{chosenSensors.map(s=>{const d=sensorWiring(s.sensor);return <div className="connection-card" key={s.sensor_id}><div className="connection-head"><div className="sensor-icon small">◈</div><div><b>{s.sensor.name}</b><span>{s.sensor.physical_pins.length} physical pins</span></div><div className="pin-badge">{d.signalPins.join(' + ')||'No signal pin'}</div></div><div className="connection-lines">{s.sensor.physical_pins.map(p=>{const row=d.rows.find(x=>x.physical.id===p.id);return <div className="connection-line" key={p.id}><span className={`line-kind ${p.role}`}>{p.role==='signal'?'SIGNAL':p.role.toUpperCase()}</span><b>{p.label}</b><span className="line-arrow">→</span><strong>{p.role==='signal'?(row?.assignment?pinLabel(row.assignment):'assigned automatically'):(p.role==='power'?'Arduino 5V':'Arduino GND')}</strong></div>})}</div>{s.sensor.id==='dht11'&&<div className="connection-note">DHT11 has 3 pins: VCC, DATA and GND. Temperature and humidity are two measurements carried over the same DATA wire, so both use the same Arduino signal pin.</div>}</div>})}</div></div></Wizard>}
  {step===6&&<Wizard title="Create your device" subtitle="DeviceOS now generates Gateway-compatible firmware, compiles it and can upload it directly to the connected Arduino."><div className="build-center"><div className="build-orbit"><span>CONFIG</span><span>FIRMWARE</span><span>ARDUINO</span></div><div className="ready-icon">✓</div><h3>{buildResult?.success?'Firmware ready':'Setup ready'}</h3><p>{currentMachine?.name} · {selected.length} sensors · {measurements} measurements · {new Set(wiring.map(w=>w.pin)).size} signal pins</p><div className="build-actions"><button className="primary big" disabled={busy} onClick={build}>{busy?'Building…':'Generate & build firmware'} <span>→</span></button><button className="primary big" disabled={!buildResult?.success||uploading} onClick={upload}>{uploading?'Uploading…':'Upload to Arduino'} <span>↑</span></button><button className="secondary" onClick={detect}>Detect Arduino</button></div>{detected.length>0&&<div className="notice success">Arduino detected on <b>{detected[0].address}</b></div>}{notice&&<div className="notice">{notice}</div>}{buildResult&&!buildResult.success&&<pre className="build-output">{buildResult.stdout||''}{buildResult.stderr||''}</pre>}</div></Wizard>}
 </>;
 const advanced=<Wizard title="Advanced DeviceOS" subtitle="Technical controls for the same machine configuration used by Visual mode."><div className="advanced-grid"><div className="advanced-card"><h3>Configuration</h3><label>Machine<select value={machine} onChange={e=>setMachine(e.target.value)}>{machines.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Controller<select value={board} onChange={e=>setBoard(e.target.value)}>{boards.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></div><div className="advanced-card"><h3>Selected sensors</h3>{chosenSensors.map(s=><div className="advanced-row" key={s.sensor_id}><b>{s.sensor.name}</b><span>{s.parameter_ids.join(', ')}</span></div>)}</div><div className="advanced-card full"><h3>Hardware actions</h3><div className="advanced-actions"><button className="primary" onClick={validate}>Validate</button><button className="secondary" onClick={loadWiring}>Generate wiring</button><button className="secondary" onClick={build}>Compile firmware</button><button className="secondary" onClick={detect}>Detect Arduino</button><button className="secondary" disabled={!buildResult?.success||uploading} onClick={upload}>Upload firmware</button></div></div>{notice&&<div className="notice">{notice}</div>}</div></Wizard>;
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">M</div><div><strong>Maintain.ai</strong><span>DeviceOS</span></div></div><div className="mode-switch"><button className={mode==='visual'?'active':''} onClick={()=>setMode('visual')}>Visual</button><button className={mode==='advanced'?'active':''} onClick={()=>setMode('advanced')}>Advanced</button></div>{mode==='visual'&&<><div className="side-title">BUILD YOUR MACHINE</div><div className="side-steps">{steps.map((s,i)=><button key={s} className={`side-step ${step===i?'active':''} ${step>i?'done':''}`} onClick={()=>i<=step&&setStep(i)}><span>{step>i?'✓':i+1}</span>{s}</button>)}</div></>}</aside><main className="main"><div className="topbar"><div><p className="eyebrow">MAINTAIN.AI DEVICEOS</p><h1>{mode==='visual'?'Machine setup':'Advanced configuration'}</h1></div><div className={connected?'connection live':'connection'}><span className="status-dot live"/> {connected?'Arduino connected':'USB device not connected'}</div></div>{mode==='visual'&&<div className="progress"><div style={{width:`${((step+1)/steps.length)*100}%`}}/></div>}{mode==='visual'?visual:advanced}{mode==='visual'&&step>0&&step<6&&<div className="wizard-footer"><button className="back" onClick={()=>setStep(s=>Math.max(0,s-1))}>← Back</button><button className="primary" onClick={next}>{step===5?'Continue to build':'Continue'} <span>→</span></button></div>}{mode==='visual'&&step===6&&<div className="wizard-footer"><button className="back" onClick={()=>setStep(5)}>← Back</button><span/></div>}{notice&&mode==='advanced'&&<div className="toast">{notice}</div>}</main></div>;
}
export default App;
